if (!nzchar(Sys.getenv("QUARTO_PROJECT_RENDER_ALL"))) {
  quit()
}

fs::file_copy("../README.md", "index.md", overwrite = TRUE)

new_content <- readLines("index.md", warn = FALSE)
new_content <- c(
  "<!-- ============ -->",
  "<!-- THIS FILE IS AUTOMATICALLY GENERATED. -->",
  "<!-- MODIFY THE README INSTEAD. -->",
  "<!-- ============ -->",
  "",
  new_content
)
writeLines(new_content, con = "index.md")
