---
title: Rules
toc: false
---

All rules belong to at least one category:

-   **comments** (COMM): mistakes in the suppression comments (`# jarl-ignore`).
-   **correctness** (CORR): code that is outright wrong or useless.
-   **dplyr** (DPLYR): rules for the package `dplyr`. Disabled by default.
-   **performance** (PERF): code that can be written to run faster.
-   **readability** (READ): code is correct but can be written in a way that is easier to read.
-   **suspicious** (SUSP): code that is most likely wrong or useless.
-   **testthat** (TESTTHAT): rules for the package `testthat`. Disabled by default.

You can find the list of available rules below, and more detailed explanations and examples in pages in the sidebar.

::: {.callout-note}
## Comparison to `lintr`

`lintr` includes many rules related to code formatting, such as [`brace_linter`](https://lintr.r-lib.org/dev/reference/brace_linter.html), [`line_length_linter`](https://lintr.r-lib.org/dev/reference/line_length_linter.html), and [`paren_body_linter`](https://lintr.r-lib.org/dev/reference/paren_body_linter.html), among others.

**Supporting those rules is not an objective of Jarl.**
Instead, I recommend using the [Air formatter](https://posit-dev.github.io/air/).
:::

The column "Has fix" can take the following values:

-   ✅ Safe fix

-   ❗ Unsafe fix

-   ❌ No fix

```{css, eval=TRUE, echo=FALSE}
.Reactable {
	background-color: transparent !important;
}

.rt-text-content, .rt-td-inner {
  color: #303d64
}

.rt-filter {
	background-color: transparent !important;
}
```

```{r, eval=TRUE, echo=FALSE, warning=FALSE}
library(reactable)
dat <- as.data.frame(
  rbind(
    c("all_equal", "suspicious", "❗", ""),
    c("any_duplicated", "performance", "✅", ""),
    c("any_is_na", "performance", "✅", ""),
    c("assignment", "readability", "✅", "Disabled by default"),
    c("blanket_suppression", "comments", "❌", ""),
    c("browser", "correctness", "❌", ""),
    c("class_equals", "suspicious", "❗", ""),
    c("coalesce", "readability", "✅", "R >= 4.4"),
    c("comparison_negation", "readability", "✅", ""),
    c("dplyr_filter_out", "dplyr", "✅", "Disabled by default"),
    c("dplyr_group_by_ungroup", "dplyr", "✅", "Disabled by default"),
    c("download_file", "suspicious", "❌", ""),
    c("duplicated_arguments", "suspicious", "❌", ""),
    c("duplicated_function_definition", "correctness", "❌", ""),
    c("empty_assignment", "readability", "❌", ""),
    c("empty_file", "suspicious", "❌", ""),
    c("equals_na", "correctness", "✅", ""),
    c("equals_nan", "correctness", "✅", ""),
    c("equals_null", "correctness", "✅", ""),
    c("expect_length", "testthat", "✅", "Disabled by default"),
    c("expect_match", "testthat", "✅", "Disabled by default"),
    c("expect_named", "testthat", "✅", "Disabled by default"),
    c("expect_no_match", "testthat", "✅", "Disabled by default"),
    c("expect_not", "testthat", "✅", "Disabled by default"),
    c("expect_null", "testthat", "✅", "Disabled by default"),
    c("expect_s3_class", "testthat", "✅", "Disabled by default"),
    c("expect_true_false", "testthat", "✅", "Disabled by default"),
    c("expect_type", "testthat", "✅", "Disabled by default"),
    c("fixed_regex", "performance", "✅", "Disabled by default"),
    c("for_loop_dup_index", "correctness, suspicious", "❌", ""),
    c("for_loop_index", "readability", "❌", ""),
    c("grepv", "readability", "✅", "R >= 4.5"),
    c("if_always_true", "readability, suspicious", "❌", ""),
    c("implicit_assignment", "readability", "❌", ""),
    c("internal_function", "suspicious", "❌", ""),
    c("invalid_chunk_suppression", "comments", "❌", ""),
    c("is_numeric", "readability", "✅", ""),
    c("length_levels", "readability", "✅", ""),
    c("length_test", "correctness", "✅", ""),
    c("lengths", "performance, readability", "✅", ""),
    c("list2df", "performance, readability", "✅", "R >= 4.0"),
    c("matrix_apply", "performance", "✅", ""),
    c("misnamed_suppression", "comments", "❌", ""),
    c("misplaced_file_suppression", "comments", "❌", ""),
    c("misplaced_suppression", "comments", "❌", ""),
    c("notin", "readability", "✅", "R >= 4.6"),
    c("numeric_leading_zero", "readability", "✅", ""),
    c("nzchar", "performance", "❗", "Disabled by default"),
    c("outer_negation", "performance, readability", "✅", ""),
    c("pipe_consistency", "readability", "✅", "Disabled by default. R >= 4.2"),
    c("quotes", "readability", "✅", "Disabled by default"),
    c("redundant_equals", "readability", "✅", ""),
    c("redundant_ifelse", "correctness, performance, readability", "✅", ""),
    c("repeat", "readability", "✅", ""),
    c("sample_int", "readability", "✅", ""),
    c("seq", "suspicious", "✅", ""),
    c("seq2", "suspicious", "✅", ""),
    c("sort", "performance, readability", "✅", ""),
    c("sprintf", "correctness, suspicious", "✅", ""),
    c("string_boundary", "performance, readability", "✅", ""),
    c("system_file", "readability", "✅", ""),
    c("true_false_symbol", "readability", "❌", ""),
    c("undesirable_function", "correctness", "❌", ""),
    c("unexplained_suppression", "comments", "❌", ""),
    c("unmatched_range_suppression", "comments", "❌", ""),
    c("unnecessary_nesting", "readability", "✅", "Disabled by default"),
    c("unreachable_code", "readability, suspicious", "❌", ""),
    c("unused_function", "correctness", "❌", ""),
    c("unused_suppression", "comments", "❌", ""),
    c("vector_logic", "performance", "❌", ""),
    c("which_grepl", "performance, readability", "✅", "")
  )
)
names(dat) <- c("Rule name", "Group", "Has fix", "Conditions")

reactable(
  dat,
  columns = list(
    `Rule name` = colDef(cell = function(value) {
      htmltools::tags$a(
        href = paste0("rules/", value, ".html"),
        target = "_blank",
        value
      )
    })
  ),
  defaultPageSize = 1000,
  filterable = TRUE
)
```
